<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.mds.platform</groupId>
    <artifactId>mds-platform</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../mds-platform/pom.xml</relativePath>
  </parent>

  <groupId>com.mds</groupId>
  <artifactId>spring-retry-pattern</artifactId>
  <version>0.1.6-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>spring-retry-pattern</name>
  <description>A reusable Spring Boot library that centralizes and standardizes retry logic using Spring Retry and Resilience4j, enabling resilient communication across services.</description>

  <properties>
    <!-- Java compile version -->
    <java.version>21</java.version>

    <!-->External Properties<-->
    <resilience4j-spring-boot3.version>2.3.0</resilience4j-spring-boot3.version>

    <!-->Plugins<-->
    <fmt-maven-plugin.version>2.13</fmt-maven-plugin.version>
  </properties>

  <dependencies>
    <!-- ======================== -->
    <!-- Spring Boot Base         -->
    <!-- ======================== -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aspectj</artifactId>
    </dependency>

    <!-- ======================== -->
    <!-- External Libraries       -->
    <!-- ======================== -->
    <dependency>
      <groupId>io.github.resilience4j</groupId>
      <artifactId>resilience4j-spring-boot3</artifactId>
      <version>${resilience4j-spring-boot3.version}</version>
    </dependency>

    <!-- ======================== -->
    <!-- Optional / Provided      -->
    <!-- ======================== -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>

    <!-- ======================== -->
    <!-- Test                     -->
    <!-- ======================== -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
      </plugin>

      <plugin>
        <groupId>com.coveo</groupId>
        <artifactId>fmt-maven-plugin</artifactId>
        <version>${fmt-maven-plugin.version}</version>
        <configuration>
          <skip>true</skip>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>format</goal>
            </goals>
            <phase>process-sources</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
